// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Employee, EmployeesService } from './employees.service';
import { Workbook } from 'exceljs';
import saveAs from 'file-saver';
import { exportDataGrid } from 'devextreme/excel_exporter';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  employees: Employee[] = [];
  selectedEmployee: Employee;
  expanded: Boolean = true;

  constructor(service: EmployeesService) {
    this.employees = service.getEmployees();
    this.selectEmployee = this.selectEmployee.bind(this);
  }

  selectEmployee(e) {
    e.component.byKey(e.currentSelectedRowKeys[0]).done(employee => {
      if(employee) {
        this.selectedEmployee = employee;
      }
    });
  }

  exportGrid(e) {
    const workbook = new Workbook(); 
    const worksheet = workbook.addWorksheet("Main sheet"); 
    exportDataGrid({ 
        worksheet: worksheet, 
        component: e.component
    }).then(function() {
        workbook.xlsx.writeBuffer().then(function(buffer: BlobPart) { 
            saveAs(new Blob([buffer], { type: "application/octet-stream" }), "DataGrid.xlsx"); 
        }); 
    }); 
    e.cancel = true; 
  }
}

<div id="app-container">
  <dx-data-grid id="dataGrid"
    [dataSource]="employees"
    keyExpr="EmployeeID"
    [allowColumnResizing]="true"
    [columnAutoWidth]="true"
    [allowColumnReordering]="true"
    (onSelectionChanged)="selectEmployee($event)"
    (onExporting)="exportGrid($event)">
    <dxi-column dataField="FullName" [fixed]="true">
      <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-column>
    <dxi-column dataField="Position">
      <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-column>
    <dxi-column
      dataField="BirthDate"
      dataType="date"
      [width]="100">
      <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-column>
    <dxi-column
      dataField="HireDate"
      dataType="date"
      [width]="100">
      <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-column>
    <dxi-column dataField="City"></dxi-column>
    <dxi-column
      dataField="Country"
      [groupIndex]="0"
      sortOrder="asc">
      <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-column>
    <dxi-column dataField="Address"></dxi-column>
    <dxi-column dataField="HomePhone"></dxi-column>
    <dxi-column dataField="PostalCode" [visible]="false"></dxi-column>
    <dxo-column-chooser [enabled]="true"></dxo-column-chooser>
    <dxo-column-fixing [enabled]="true"></dxo-column-fixing>
    <dxo-filter-row [visible]="true"></dxo-filter-row>
    <dxo-search-panel [visible]="true"></dxo-search-panel>
    <dxo-group-panel [visible]="true"></dxo-group-panel>
    <dxo-selection mode="single"></dxo-selection>
    <dxo-summary>
      <dxi-group-item
        summaryType="count">
      </dxi-group-item>
    </dxo-summary>
    <dxo-editing
      mode="popup"
      [allowUpdating]="true"
      [allowDeleting]="true"
      [allowAdding]="true">
    </dxo-editing>
    <dxo-grouping [autoExpandAll]="expanded"></dxo-grouping>
    <dxo-toolbar>
        <dxi-item name="groupPanel"></dxi-item>
        <dxi-item location="after">
            <dx-button
                [text]="expanded ? 'Collapse All' : 'Expand All'"
                [width]="136"
                (onClick)="expanded = !expanded">
            </dx-button>
        </dxi-item>
        <dxi-item name="addRowButton" showText="always"></dxi-item>
        <dxi-item name="exportButton"></dxi-item>
        <dxi-item name="columnChooserButton"></dxi-item>
        <dxi-item name="searchPanel"></dxi-item>
    </dxo-toolbar>
    <dxo-master-detail
      [enabled]="true"
      [template]="'employee-info'">
    </dxo-master-detail>
    <div *dxTemplate="let employee of 'employee-info'">
      <img class="employee-photo" [src]="employee.data.Photo">
      <p class="employee-notes">{{ employee.data.Notes }}</p>
    </div>
    <dxo-export [enabled]="true"></dxo-export>
    
  </dx-data-grid>
  <p id="selected-employee" *ngIf="selectedEmployee">
    Selected employee: {{ selectedEmployee.FullName }}
  </p>
</div>

// react/src/App.js
import React, { useState } from 'react';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import {
  DataGrid,
  ColumnChooser,
  ColumnFixing,
  Column,
  RequiredRule,
  FilterRow,
  SearchPanel,
  GroupPanel,
  Selection,
  Summary,
  GroupItem,
  Editing,
  Grouping,
  Toolbar,
  Item,
  MasterDetail,
  Export
} from 'devextreme-react/data-grid';
import { Button } from 'devextreme-react/button';
import { employees } from './employees';
import { Workbook } from 'exceljs';
import saveAs from 'file-saver';
import { exportDataGrid } from 'devextreme/excel_exporter';

function SelectedEmployee(props) {
  if(props.employee) {
    return (
      <p id="selected-employee">
        Selected employee: {props.employee.FullName}
      </p>
    );
  }
  return null;
}

function DetailSection(props) {
  const employee = props.data.data;
  return (
    <div>
      <img
        className="employee-photo"
        alt={employee.FullName}
        src={employee.Photo}
      />
      <p className="employee-notes">{employee.Notes}</p>
    </div>
  );
}

function exportGrid(e) {
  const workbook = new Workbook(); 
  const worksheet = workbook.addWorksheet("Main sheet"); 
  exportDataGrid({ 
      worksheet: worksheet, 
      component: e.component
  }).then(function() {
      workbook.xlsx.writeBuffer().then(function(buffer) { 
          saveAs(new Blob([buffer], { type: "application/octet-stream" }), "DataGrid.xlsx"); 
      }); 
  });
  e.cancel = true; 
}

function App() {
  const [selectedEmployee, setSelectedEmployee] = useState();
  const [expanded, setExpanded] = useState(true);
  const selectEmployee = (e) => {
    e.component.byKey(e.currentSelectedRowKeys[0]).done(employee => {
        setSelectedEmployee(employee);
    });
  }

  return (
    <div className="App">
      <DataGrid
        id="dataGrid"
        dataSource={employees}
        keyExpr="EmployeeID"
        allowColumnResizing={true}
        columnAutoWidth={true}
        allowColumnReordering={true}
        onSelectionChanged={selectEmployee}
        onExporting={exportGrid}>
        <ColumnChooser enabled={true} />
        <Column dataField="FullName">
          <RequiredRule />
        </Column>
        <Column dataField="Position">
          <RequiredRule />
        </Column>
        <Column
          dataField="BirthDate"
          dataType="date"
          width={100}>
          <RequiredRule />
        </Column>
        <Column
          dataField="HireDate"
          dataType="date"
          width={100}>
          <RequiredRule />
        </Column>
        <Column dataField="City" />
        <Column
          dataField="Country"
          groupIndex={0}
          sortOrder="asc">
          <RequiredRule />
        </Column>
        <Column dataField="Address" />
        <Column dataField="HomePhone" />
        <Column dataField="PostalCode" visible={false} />
        <ColumnFixing enabled={true} />
        <FilterRow visible={true} />
        <SearchPanel visible={true} />
        <GroupPanel visible={true} />
        <Selection mode="single" />
        <Summary>
          <GroupItem
            summaryType="count"
          />
        </Summary>
        <Editing
          mode="popup"
          allowUpdating={true}
          allowDeleting={true}
          allowAdding={true}
        />
        <Grouping autoExpandAll={expanded} />
        <Toolbar>
          <Item name="groupPanel" />
          <Item location="after">
            <Button
                text={expanded ? 'Collapse All' : 'Expand All'}
                width={136}
                onClick={() => setExpanded(prevExpanded => !prevExpanded)}
            />
          </Item>
          <Item name="addRowButton" showText="always" />
          <Item name="exportButton" />
          <Item name="columnChooserButton" />
          <Item name="searchPanel" />
        </Toolbar>
        <MasterDetail
          enabled={true}
          component={DetailSection}
        />
        <Export enabled={true} />
      </DataGrid>
      <SelectedEmployee employee={selectedEmployee} />
    </div>
  );
}

export default App;
